### ISSUE TITLE
How to write file use Shizuku service

### ISSUE THREAD

**Issue by n0xgg04** [MagicianGuo/Android-FileExplorerDemo#1]
I want to make a function to write file use Shizuku. But it quite not running when i use ``File`` class to access file. Please give me some advice. I want to use it to write/read on ``Android/data`` in Android 14

**Comment by MagicianGuo** [comment]
> I want to make a function to write file use Shizuku. But it quite not running when i use ``File`` class to access file. Please give me some advice. I want to use it to write/read on ``Android/data`` in Android 14

Please start Shizuku and keep it running. Then run my latest code and grant permissions to the application. The directory should be accessible.
