### ISSUE TITLE
方便加个微信或者qq吗

### ISSUE THREAD

**Issue by zhangruiyu** [MagicianGuo/Android-FileExplorerDemo#3]
想付费请求做个demo😂

**Comment by MagicianGuo** [comment]
> 想付费请求做个demo😂

目前没这个打算😷平时还是比较忙的

**Comment by zhangruiyu** [comment]
emmm  就是安卓授权这个我发现了一个新方案
我不是学生 就是简单做个新的授权,一样是docfile那种方式

**Comment by zhangruiyu** [comment]
方便加个v吗  简单聊一下0-0 不耽误几分钟

**Comment by MagicianGuo** [comment]
久等了，这个新方法我已经知道了，目前最新代码已做适配～

**Comment by zhangruiyu** [comment]
哈哈，我上周已经成功啦，确实可以
