### ISSUE TITLE
你好，vivos15  在Android 13和14两个版本上， 还是无法获取授权，具体看下图

### ISSUE THREAD

**Issue by LittleSillyGirl** [MagicianGuo/Android-FileExplorerDemo#4]
![Screenshot_20240921_111255](https://github.com/user-attachments/assets/7d64b9f3-15d1-4b67-9e79-1774e06ccd81)
![Screenshot_20240921_111301](https://github.com/user-attachments/assets/145c7790-f68d-46da-9c46-1576ca9e2d34)
![微信截图_20240921112706](https://github.com/user-attachments/assets/2ff6bc91-c7f3-4095-8805-792cee30cfe6)

**Comment by MagicianGuo** [comment]
> ![Screenshot_20240921_111255](https://github.com/user-attachments/assets/7d64b9f3-15d1-4b67-9e79-1774e06ccd81)
> ![Screenshot_20240921_111301](https://github.com/user-attachments/assets/145c7790-f68d-46da-9c46-1576ca9e2d34)
> ![微信截图_20240921112706](https://github.com/user-attachments/assets/2ff6bc91-c7f3-4095-8805-792cee30cfe6)
> 

这个是正常现象，安卓高版本的系统已经把这个授权方式封锁了，需要借助shizuku授权。激活shizuku，然后给此应用授权就好了。

**Comment by MagicianGuo** [comment]
> ![Screenshot_20240921_111255](https://github.com/user-attachments/assets/7d64b9f3-15d1-4b67-9e79-1774e06ccd81)
> ![Screenshot_20240921_111301](https://github.com/user-attachments/assets/145c7790-f68d-46da-9c46-1576ca9e2d34)
> ![微信截图_20240921112706](https://github.com/user-attachments/assets/2ff6bc91-c7f3-4095-8805-792cee30cfe6)
> 

这个是正常现象，安卓14推出几个月后谷歌推出补丁把这个授权方式封锁了，这个补丁可能也会被厂商应用于低版本的系统上。这种情况需要借助shizuku授权。激活shizuku，然后给此应用授权就好了。
