### ISSUE TITLE
在部分特殊版本依旧无法授权

### ISSUE THREAD

**Issue by ycccccccy** [MagicianGuo/Android-FileExplorerDemo#5]
经过测试，在A12，安全补丁日期2022/4/5的系统上可以授权
在A12，安全补丁日期2024/9/1的系统上也可以授权
但是在A12，安全补丁日期2024/3/1的系统上无法授权

无法授权时的情况于VIVOOS15的那个issue情况一样，无论是使用A13还是5月份的新uri构造方式都是无法授权

**Comment by MagicianGuo** [comment]
> 经过测试，在A12，安全补丁日期2022/4/5的系统上可以授权
> 在A12，安全补丁日期2024/9/1的系统上也可以授权
> 但是在A12，安全补丁日期2024/3/1的系统上无法授权
> 
> 无法授权时的情况于VIVOOS15的那个issue情况一样，无论是使用A13还是5月份的新uri构造方式都是无法授权

这是厂商搞的，把uri授权封锁了，只能用shizuku授权访问。
